FROM python:3.12.3-slim

WORKDIR /usr/src/app

COPY ./manager/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./manager .
COPY ./tool ./tool
COPY ./crew ./crew


CMD [ "python", "app.py" ]