FROM python:3.12.3-slim

WORKDIR /usr/src/app

# RUN pip install --upgrade pip setuptools wheel
RUN pip install poetry

COPY ./manager/pyproject.toml .
COPY ./manager/poetry.lock .

RUN poetry config virtualenvs.create false && poetry install && rm -rf /root/.cache

COPY ./manager .
COPY ./tool ./tool
COPY ./crew ./crew


CMD ["sh", "-c", "python load_config_to_redis.py && python app.py"]
