

FROM node:20.17.0 AS build-stage

WORKDIR /home/user/root/app

COPY package*.json ./
RUN npm ci 

COPY . .

ARG CONFIG=production
RUN npm run build -- --configuration=$CONFIG

FROM nginx:alpine AS production-stage

COPY --from=build-stage /home/user/root/app/dist/frontend-crewai/browser/ /usr/share/nginx/html/


# Copy the custom error page
COPY 50x.html /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

