import { GetProjectRequest } from '../models/project.model';

/**
 * Mock template projects for UI demonstration
 */
export const TEMPLATE_PROJECTS: GetProjectRequest[] = [
  {
    id: 1001,
    name: 'Hierarchical Research Assistant',
    description:
      'A template for creating a hierarchical template for creating a hierarchicaltemplate for creating a hierarchical team of agents that can perform research on any topic with a manager agent and specialized researcher agents.',
    process: 'hierarchical',
    tasks: [],
    agents: [],
    memory: false,
    planning: false,
    config: null,
    max_rpm: null,
    cache: null,
    full_output: true,
    default_temperature: 0.7,
    planning_llm_config: null,
    manager_llm_config: null,
    embedding_config: null,
    tags: [1, 2, 3],
  },
  {
    id: 1002,
    name: 'Sequential Data Pipeline',
    description:
      'A template for creating a sequential workflow of agents that process data in a pipeline fashion - from collection to analysis to reporting.',
    process: 'sequential',
    tasks: [],
    agents: [],
    memory: false,
    planning: false,
    config: null,
    max_rpm: null,
    cache: null,
    full_output: true,
    default_temperature: 0.7,
    planning_llm_config: null,
    manager_llm_config: null,
    embedding_config: null,
    tags: [4, 5, 6],
  },
  {
    id: 1003,
    name: 'Customer Support Bot',
    description:
      'A template for creating a customer support agent that can understand queries, search knowledge bases, and provide helpful responses.',
    process: 'sequential',
    tasks: [],
    agents: [],
    memory: true,
    planning: false,
    config: null,
    max_rpm: null,
    cache: true,
    full_output: true,
    default_temperature: 0.5,
    planning_llm_config: null,
    manager_llm_config: null,
    embedding_config: null,
    tags: [7, 8, 9],
  },
  {
    id: 1004,
    name: 'Creative Content Team',
    description:
      'A template for a team of creative agents that collaborate to produce content - including writers, editors, and reviewers in a feedback loop.',
    process: 'hierarchical',
    tasks: [],
    agents: [],
    memory: true,
    planning: true,
    config: null,
    max_rpm: null,
    cache: true,
    full_output: true,
    default_temperature: 0.8,
    planning_llm_config: null,
    manager_llm_config: null,
    embedding_config: null,
    tags: [10, 11, 12],
  },
  {
    id: 1005,
    name: 'Code Assistant',
    description:
      'A template for a programming assistant that can help with code generation, debugging, and optimization across multiple languages.',
    process: 'sequential',
    tasks: [],
    agents: [],
    memory: true,
    planning: true,
    config: null,
    max_rpm: null,
    cache: true,
    full_output: true,
    default_temperature: 0.4,
    planning_llm_config: null,
    manager_llm_config: null,
    embedding_config: null,
    tags: [13, 14, 15],
  },
];
