FROM python:3.13

WORKDIR /home/root/installer

RUN pip install poetry
COPY . .

RUN poetry install --no-root --without win
RUN poetry run pyinstaller installer.py --name epicstaff.app --onefile --add-data 'app/templates:app/templates' --add-data 'app/static:app/static' --hidden-import engineio.async_drivers.threading --distpath /out
